"""orders data

Revision ID: e68ba9a78dc0
Revises: e8be5786aa4f
Create Date: 2025-08-01 12:58:55.638544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e68ba9a78dc0'
down_revision = 'e8be5786aa4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limit_orders', sa.Column('address', sa.String(length=42), nullable=False))
    op.add_column('limit_orders', sa.Column('order_hash', sa.String(length=66), nullable=False))
    op.add_column('limit_orders', sa.Column('data', sa.JSON(), nullable=False))
    op.drop_column('limit_orders', 'src_token_name')
    op.drop_column('limit_orders', 'created_at')
    op.drop_column('limit_orders', 'price')
    op.drop_column('limit_orders', 'dst_token_name')
    op.drop_column('limit_orders', 'amount')
    op.drop_column('limit_orders', 'updated_at')
    op.drop_column('limit_orders', 'dst_token_address')
    op.drop_column('limit_orders', 'expiration')
    op.drop_column('limit_orders', 'src_token_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limit_orders', sa.Column('src_token_address', sa.VARCHAR(length=42), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('expiration', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('dst_token_address', sa.VARCHAR(length=42), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('amount', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('dst_token_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('price', sa.NUMERIC(precision=38, scale=18), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('limit_orders', sa.Column('src_token_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('limit_orders', 'data')
    op.drop_column('limit_orders', 'order_hash')
    op.drop_column('limit_orders', 'address')
    # ### end Alembic commands ### 