"""Initial migration for LimitOrder model

Revision ID: e8be5786aa4f
Revises: 
Create Date: 2025-07-31 00:53:39.557752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8be5786aa4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limit_orders',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.Column('src_token_name', sa.String(length=255), nullable=False),
    sa.Column('src_token_address', sa.String(length=42), nullable=False),
    sa.Column('dst_token_name', sa.String(length=255), nullable=False),
    sa.Column('dst_token_address', sa.String(length=42), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('limit_orders')
    # ### end Alembic commands ### 